services:
  _defaults:
    public: true
    bind:
      $logger: '@monolog.logger.contao'

  HeimrichHannot\ContaoListGridBundle\:
    resource: '../../{EventListener}/'
    autowire: true
    autoconfigure: true

  huh.listgrid.listener.callbacks:
    class: HeimrichHannot\ContaoListGridBundle\EventListener\CallbackListener
    arguments: ['@contao.framework']